export const ADD_CREATIVES = 'ADD_CREATIVES';
export const ADD_CAMPAIGNS = 'ADD_CAMPAIGNS';
export const DELETE_CREATIVE = 'DELETE_CREATIVE';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const GET_CREATIVE = 'GET_CREATIVE';
